add-bookings v1.1
valeriyDd/java-shareit pull request #3
Opened 2023-06-13 11:25 UTC by valeriyDd

2023-06-13 13:08 UTC, valeriyDd commented
Добрый день, попробовал сразу учесть прошлые замечания про дубликаты, вроде бы все учел, но мог просмотреть. В целом было сложно :D

2023-06-13 21:02 UTC, z8q requested changes

2023-06-13 21:02 UTC, z8q commented on src/main/java/ru/practicum/shareit/item/ItemRepository.java
> +     * @param owner - owner id
попробуй навести курсор на метод findAllByOwnerId.
Появится сообщение из java-doc где будет:
`Params: owner – - owner id`
Знак тире лишний)

2023-06-13 21:02 UTC, z8q commented on src/main/java/ru/practicum/shareit/user/UserController.java
> +            @RequestBody UserDto userDto) {
При update UserDto не валидируется.
Возникает возможность отправить что-то такое:
PATCH http://localhost:8080/users/1
{
	"name": "Bob",
	"email": "@bob@yandex.ru"
}

В ItemController тоже такое есть

2023-06-14 20:54 UTC, z8q requested changes

2023-06-14 20:54 UTC, z8q commented on src/main/java/ru/practicum/shareit/user/UserController.java
> +            @RequestBody UserDto userDto) {
Здесь отсутствие валидации сохраняется

2023-06-15 19:27 UTC, z8q requested changes

2023-06-15 19:27 UTC, z8q commented on src/main/java/ru/practicum/shareit/user/dto/UserDto.java
> +    @Email(groups = {UpdateValidationGroup.class, CreateValidationGroup.class})
При PATCH http://localhost:8080/users/1
{
	"name": "Bob",
	"email": ""
}
удается стереть email пользователю 

При GET http://localhost:8080/users
возвращается:
```
[
	{
		"id": 1,
		"name": "Bob",
		"email": ""
	}
]
```

2023-06-15 19:33 UTC, z8q commented on src/main/java/ru/practicum/shareit/user/dto/UserDto.java
> +    @Email(groups = {UpdateValidationGroup.class, CreateValidationGroup.class})
С вещами такая же история
PATCH http://localhost:8080/items/1
{
	"name": "",
	"description": "",
	"available": true
}

Позволяет сохранить

2023-06-16 13:45 UTC, valeriyDd commented
Надеюсь сейчас уже все, а то у меня от этих Бобов крыша едет :D
2 часа не мог понять почему тесты крашатся, оказывается просто пропустил "!"

2023-06-16 19:40 UTC, z8q approved these changes

2023-06-17 17:05 UTC, merged