add-item-requests
valeriyDd/java-shareit pull request #4
Opened 2023-06-18 14:12 UTC by valeriyDd

2023-06-19 21:24 UTC, z8q requested changes

2023-06-19 21:24 UTC, z8q commented on src/main/java/ru/practicum/shareit/user/UserController.java
>      public UserDto update(
Удается обновить объект с пустой почтой:
PATCH http://localhost:8080/users/1
{
	"name": "bob",
	"email": ""
}
Сохраняется с пустым полем

2023-06-19 21:24 UTC, z8q commented on src/main/java/ru/practicum/shareit/item/ItemController.java
>      public ItemDto update(@RequestHeader(value = "X-Sharer-User-Id", required = false) long userId,
Есть возможность обновить объект с пустыми name и description:
{
	"name": "",
	"description": "",
	"available": true
}

2023-06-20 10:10 UTC, valeriyDd commented on src/main/java/ru/practicum/shareit/item/ItemController.java
>      public ItemDto update(@RequestHeader(value = "X-Sharer-User-Id", required = false) long userId,
Спасибо, поправил :)

2023-06-20 17:39 UTC, z8q approved these changes

2023-06-20 17:39 UTC, z8q commented on src/main/java/ru/practicum/shareit/item/ItemServiceImpl.java
> +        if (itemDto.getName() != null && !itemDto.getName().isBlank()) item.setName(itemDto.getName());
Можно было бы эту проверку тоже сделать через аннотацию

2023-06-21 08:38 UTC, merged